version: '3.9'

services:

  influxdb:
    image: influxdb:latest
    container_name: rpi-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage-data:/var/lib/influxdb2
      - influxdb-storage-config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: 260w # 5 Years = 5*52w

  telegraf_with_python:
    build: ./telegraf_with_python/
    container_name: rpi-telegraf
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    depends_on:
      - influxdb
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/hostfs:ro
      - ./air_quality:/etc/scripts/air_quality:ro
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      OPENWEATHERMAP_APPID: ${OPENWEATHERMAP_APPID}
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs

  grafana:
    image: grafana/grafana:latest
    container_name: rpi-grafana
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./etc/grafana-provisioning/:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_INSTALL_PLUGINS: grafana-strava-datasource,grafana-worldmap-panel,yesoreyeram-infinity-datasource,grafana-clock-panel
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      STRAVA_REFRESH_TOKEN: ${STRAVA_REFRESH_TOKEN}

volumes:
  grafana-storage:
  influxdb-storage-data:
  influxdb-storage-config:
