{
 "title": "Telegraf",
 "description": "Telegraf dashboard intended to give you a general system overview.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "source", "label": "Datasource", "query": "influxdb" },
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Current State", "type": "alertlist", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 } },
  { "title": "Recent Changes", "type": "alertlist", "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 } },
  {
   "title": "CPU Used Percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=", "value": "cpu-total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Used",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Volume used percent",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT mean(\"usage_guest\") AS \"guest\", mean(\"usage_guest_nice\") AS \"guest_nice\", mean(\"usage_iowait\") AS \"iowait\", mean(\"usage_irq\") AS \"irq\", mean(\"usage_nice\") AS \"nice\", mean(\"usage_softirq\") AS \"softirq\", mean(\"usage_steal\") AS \"steal\", mean(\"usage_system\") AS \"system\", mean(\"usage_user\") AS \"user\" FROM \"autogen\".\"cpu\" WHERE (\"cpu\" = 'cpu-total' AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "usage_guest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "guest" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_guest_nice" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "guest_nice" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "iowait" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_irq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "irq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_nice" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "nice" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_softirq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "softirq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "steal" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "user" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "cpu", "operator": "=", "value": "cpu-total" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "AVG CPU per core",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT sum(\"usage_guest\")+sum(\"usage_guest_nice\") FROM \"cpu\" WHERE (\"cpu\" != 'cpu-total') AND $timeFilter GROUP BY time($__interval), \"cpu\" fill(null)",
       "select": [
        [
         { "params": [ "usage_active" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "cpu", "operator": "!=", "value": "cpu-total" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Load/Memory/Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "system",
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "shortterm" ], "type": "alias" }
        ],
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "midterm" ], "type": "alias" }
        ],
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "longterm" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "mem",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "available" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "free" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Swap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "swap",
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "used_percent" ], "type": "alias" }
        ],
        [
         { "params": [ "in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "processes",
       "query": "SELECT 100 - mean(\"Percent_Idle_Time\") FROM \"win_cpu\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "blocked" ], "type": "alias" }
        ],
        [
         { "params": [ "idle" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "idle" ], "type": "alias" }
        ],
        [
         { "params": [ "sleeping" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "sleeping" ], "type": "alias" }
        ],
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "running" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "running" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "interface" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "net",
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "rx" ], "type": "alias" }
        ],
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "tx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "interface", "operator": "!=", "value": "all" },
        { "condition": "AND", "key": "interface", "operator": "!~", "value": "/br-/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Througput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_derivative(mean(\"read_bytes\"), 1s) AS \"reads\", non_negative_derivative(mean(\"write_bytes\"), 1s) AS \"writes\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND (\"name\" =~ /[s,v]d[a-z]$/ OR \"name\" =~ /:/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(none)",
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "reads" ], "type": "alias" }
        ],
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "writes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/[s,v]d[a-z]$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/:/" }
       ]
      }
     ]
    },
    {
     "title": "Disk IO/s",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_derivative(mean(\"reads\"), 1s) AS \"reads\", non_negative_derivative(mean(\"writes\"), 1s) AS \"writes\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND (\"name\" =~ /[s,v]d[a-z]$/ OR \"name\" =~ /:/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(none)",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "reads" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "writes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/[s,v]d[a-z]$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "diskio",
       "query": "SELECT non_negative_derivative(mean(\"read_time\"), 1s) AS \"reads\", non_negative_derivative(mean(\"write_time\"), 1s) AS \"writes\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND (\"name\" =~ /[s,v]d[a-z]$/ OR \"name\" =~ /:/) AND $timeFilter GROUP BY time($__interval), \"name\" fill(none)",
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "reads" ], "type": "alias" }
        ],
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "writes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/[s,v]d[a-z]$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPUs",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_cpus" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Running Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_running" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "memory_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Stopped Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_stopped" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Paused Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker",
       "select": [
        [
         { "params": [ "n_containers_paused" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_total"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "throughput" ], "type": "alias" }
        ],
        [
         { "params": [ "io_serviced_recursive_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "IOps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PuppetAgent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "PuppetAgent",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "puppetagent",
       "select": [
        [
         { "params": [ "time_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "time total" ], "type": "alias" }
        ],
        [
         { "params": [ "events_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "events total" ], "type": "alias" }
        ],
        [
         { "params": [ "changes_total" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "changes total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overview",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_overview",
       "select": [
        [
         { "params": [ "channels" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "channels" ], "type": "alias" }
        ],
        [
         { "params": [ "connections" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "connections" ], "type": "alias" }
        ],
        [
         { "params": [ "consumers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "consumers" ], "type": "alias" }
        ],
        [
         { "params": [ "exchanges" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "exchanges" ], "type": "alias" }
        ],
        [
         { "params": [ "messages" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "messages" ], "type": "alias" }
        ],
        [
         { "params": [ "queues" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "queues" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Exchange",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "exchange" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_exchange",
       "query": "SELECT mean(\"messages_publish_in\") AS \"in\", mean(\"messages_publish_out\") AS \"out\" FROM \"rabbitmq_exchange\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"exchange\" fill(null)",
       "select": [
        [
         { "params": [ "messages_publish_in" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "messages_publish_out" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Queue",
     "type": "graph",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "queue" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rabbitmq_queue",
       "query": "SELECT mean(\"messages_publish_in\") AS \"in\", mean(\"messages_publish_out\") AS \"out\" FROM \"rabbitmq_exchange\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time(1m), \"exchange\" fill(null)",
       "select": [
        [
         { "params": [ "consumers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "consumers" ], "type": "alias" }
        ],
        [
         { "params": [ "messages" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "messages" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HAProxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Servers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "haproxy",
       "select": [
        [
         { "params": [ "active_servers" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "backend" }
       ]
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "haproxy",
       "select": [
        [
         { "params": [ "rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "backend" },
        { "condition": "AND", "key": "sv", "operator": "=", "value": "BACKEND" }
       ]
      }
     ]
    },
    {
     "title": "Incomming Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "sv" ], "type": "tag" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "haproxy",
       "select": [
        [
         { "params": [ "bin" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "server" }
       ]
      }
     ]
    },
    {
     "title": "Outgoing Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "sv" ], "type": "tag" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "haproxy",
       "select": [
        [
         { "params": [ "bout" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "server" }
       ]
      }
     ]
    },
    {
     "title": "Server Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "sv" ], "type": "tag" },
        { "params": [ "proxy" ], "type": "tag" }
       ],
       "limit": "1",
       "measurement": "haproxy",
       "query": "SELECT \"status\" FROM \"haproxy\" WHERE (\"host\" =~ /^$host$/ AND \"type\" = 'server') AND $timeFilter GROUP BY \"sv\", \"proxy\" LIMIT 1",
       "select": [
        [
         { "params": [ "status" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "type", "operator": "=", "value": "server" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "S.M.A.R.T",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "SMART",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "smart_device",
       "select": [
        [
         { "params": [ "exit_status" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "enabled", "operator": "=", "value": "Enabled" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "smart_device",
       "select": [
        [
         { "params": [ "temp_c" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "enabled", "operator": "=", "value": "Enabled" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ZFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "ARC Size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zfs",
       "select": [
        [
         { "params": [ "arcstats_metadata_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "metadata" ], "type": "alias" }
        ],
        [
         { "params": [ "arcstats_mfu_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "mfu" ], "type": "alias" }
        ],
        [
         { "params": [ "arcstats_mru_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "mru" ], "type": "alias" }
        ],
        [
         { "params": [ "arcstats_overhead_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "overhead" ], "type": "alias" }
        ],
        [
         { "params": [ "arcstats_hdr_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "hdr" ], "type": "alias" }
        ],
        [
         { "params": [ "arcstats_dbuf_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "dbuf" ], "type": "alias" }
        ],
        [
         { "params": [ "arcstats_dnode_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "dnode" ], "type": "alias" }
        ],
        [
         { "params": [ "arcstats_size" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "ARC Hits/Misses",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zfs",
       "select": [
        [
         { "params": [ "arcstats_misses" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "misses" ], "type": "alias" }
        ],
        [
         { "params": [ "arcstats_hits" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "hits" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Pool IO/s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pool" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zfs_pool",
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "reads" ], "type": "alias" }
        ],
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "writes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Pool Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pool" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zfs_pool",
       "select": [
        [
         { "params": [ "nread" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "reads" ], "type": "alias" }
        ],
        [
         { "params": [ "nwritten" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "writes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Pool Throughput",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "pool" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zfs_pool",
       "select": [
        [
         { "params": [ "rtime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "reads" ], "type": "alias" }
        ],
        [
         { "params": [ "wtime" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "writes" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}